# nixpacks.toml

providers = ["...","python"]

[phases.setup]
nixPkgs = ["...", "wkhtmltopdf", "cairo", "pkg-config"]

[phases.install]
cmds = [
  "python3 -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "wkhtmltopdf --version && streamlit run '🏠_Home.py' --server.address 0.0.0.0 --server.port $PORT --server.fileWatcherType none --browser.gatherUsageStats false --client.toolbarMode minimal"
